### ISSUE TITLE
Error on "python manage.py filldb" 

### ISSUE THREAD

**Issue by SatejG** [gnowledge/gstudio#1204]
Getting error on "filldb" command on installation.

![screenshot from 2015-07-10 18 45 27](https://cloud.githubusercontent.com/assets/13237227/8619474/fe5822da-2734-11e5-9f0f-276019eae032.png)

Please help regarding.

**Comment by katkamrachana** [comment]
Create a folder 'schema_files' under the
gnowsys_ndf/ndf/management/commands/ and run filldb.
I will update the filldb.py to fix this error.

On Fri, Jul 10, 2015 at 6:58 PM, SatejG <notifications@github.com> wrote:

> Getting error on "filldb" command on installation.
>
> [image: screenshot from 2015-07-10 18 45 27]
> <https://cloud.githubusercontent.com/assets/13237227/8619474/fe5822da-2734-11e5-9f0f-276019eae032.png>
>
> Please help regarding.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gnowledge/gstudio/issues/1204>.
>



-- 
Regards,
Rachana Katkam

**Comment by kedar2a** [comment]
It's just an error for - unable to create a log file. It means following:
- Script ran successfully. 
- Unable to create/write-in a log file.

**Comment by gnowgi** [comment]
What could be the reason for not able to create the log file?

**Comment by katkamrachana** [comment]
The path specified for log file does not exist, i.e management/commands/
requires schema_files/ to be created under which the filldb.log will be
saved.

we just have to change the path of .log file for saving.

On Sat, Jul 11, 2015 at 1:39 PM, gnowgi <notifications@github.com> wrote:

> What could be the reason for not able to create the log file?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gnowledge/gstudio/issues/1204#issuecomment-120593972>.
>



-- 
Regards,
Rachana Katkam

**Comment by katkamrachana** [comment]
Fixed in #1209
