### ISSUE TITLE
Make file upload and file description creation asynchronous

### ISSUE THREAD

**Issue by planemad** [gnowledge/gstudio#124]
# Current user flow
- Select files to upload
- Fill out file details form
- Click submit
  > File is uploaded
  > open file list page view
  > END

IF file has been previously uploaded > Message "Following files have been previously uploaded" > END
# Required user flow
- Select or drop files to be uploaded in dropzone > Files start uploading to server > END

IF file has been previously uploaded > Mark as duplicate in dropzone > END
- Fill out file details form
- Click submit
  > open file list page view
  > END

**Comment by katkamrachana** [comment]
This has been taken care by using [hashFS](https://pypi.python.org/pypi/hashfs/) [implementation](https://github.com/gnowledge/gstudio/pull/1441) by @kedar2a
