### ISSUE TITLE
Restructure top bar navigation links

### ISSUE THREAD

**Issue by planemad** [gnowledge/gstudio#128]
Proposal below requires approval.
# Current structure
- metaStudio (#home)
- home (#home)
  - IF logged in: Group name(#group home) []
- Page (#page list)
- File (#file list)
- Group (#group list)
- Image
- Video
- Forum
- Quiz
# Optimized structure
- metaStudio (#home)
- Groups (#group list)
  - IF logged in: Group name(#group home) []
- Pages (#page list)
- Gallery (#file list; view filters for video and images)
- Forum
- Quiz

**Comment by katkamrachana** [comment]
Closing this issue as the design specifications have been updated with latest requirements.
