### ISSUE TITLE
502 Bad Gateway on /analytics/summary/ URL

### ISSUE THREAD

**Issue by ashgkwd** [gnowledge/gstudio#1366]
I gives 502 HTTP error on clicking `Analytics` nav bar dropdown link in right top corner.
Here is the complete URL "http://0.0.0.0:8180/567d02227b41a4004f2974ee/analytics/summary/"

**Comment by katkamrachana** [comment]
The Analytics module is not in action currently and has been extended/improvised  as **Counter**.  Also, the specified link is removed from drop down menu. 
The analytics is commented as of now. We may redefine or scrap it as per future requirements.
