### ISSUE TITLE
rcs restore function not working as expected

### ISSUE THREAD

**Issue by alpeshgajbe** [gnowledge/gstudio#1514]
Tried the rcs restore function got this error @katkamrachana Please check

> root@school-server:/home/docker/code/gstudio/gnowsys-ndf# python manage.py shell
> Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
> [GCC 4.8.2] on linux2
> Type "help", "copyright", "credits" or "license" for more information.
> (InteractiveConsole)
> `>>>` execfile('../doc/deployer/restore_dump.py')
> 
>  Path --  Node
> ---
> 
> /data/rcs-repo/Nodes/3/3/3/575333e1c71f85026d3e3833.json
> 
> ============= in get_json_file():
> 
> /data/rcs-repo/Nodes/3/3/3/575333e1c71f85026d3e3833.json,v  -->  /data/rcs-repo/Nodes/3/3/3/575333e1c71f85026d3e3833.json
> revision 1.1 (locked)
> co: writable /data/rcs-repo/Nodes/3/3/3/575333e1c71f85026d3e3833.json exists; checkout aborted
> Exception while getting JSON:  [Errno 2] No such file or directory: '575333e1c71f85026d3e3833.json'
> Traceback (most recent call last):
>   File "<console>", line 1, in <module>
>   File "../doc/deployer/restore_dump.py", line 238, in <module>
>     run()
>   File "../doc/deployer/restore_dump.py", line 52, in run
>     print "======= _id : ", data['_id']
> TypeError: 'NoneType' object has no attribute '__getitem__'
> ======= _id :  >>> 
> 
> root@school-server:/home/docker/code/gstudio/gnowsys-ndf# cd /data/rcs-repo/Nodes/
> root@school-server:/data/rcs-repo/Nodes# ls
> 0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
> root@school-server:/data/rcs-repo/Nodes# cd 3/3/3/  
> root@school-server:/data/rcs-repo/Nodes/3/3/3# ls 
> 575333e1c71f85026d3e3633.json    575333e1c71f85026d3e3733.json    575333e1c71f85026d3e3833.json    575333e1c71f85026d3e3933.json
> 575333e1c71f85026d3e3633.json,v  575333e1c71f85026d3e3733.json,v  575333e1c71f85026d3e3833.json,v  575333e1c71f85026d3e3933.json,v
> root@school-server:/data/rcs-repo/Nodes/3/3/3# ls -l
> total 32
> -rw-r--r-- 1 500 500 1846 Jun 27 19:13 575333e1c71f85026d3e3633.json
> -rw-r--r-- 1 500 500 2102 Jun 27 19:13 575333e1c71f85026d3e3633.json,v
> -rw-r--r-- 1 500 500 1848 Jun 27 19:13 575333e1c71f85026d3e3733.json
> -rw-r--r-- 1 500 500 2100 Jun 27 19:13 575333e1c71f85026d3e3733.json,v
> -rw-r--r-- 1 500 500 1851 Jun 27 19:13 575333e1c71f85026d3e3833.json
> -rw-r--r-- 1 500 500 2109 Jun 27 19:13 575333e1c71f85026d3e3833.json,v
> -rw-r--r-- 1 500 500 1852 Jun 27 19:13 575333e1c71f85026d3e3933.json
> -rw-r--r-- 1 500 500 2112 Jun 27 19:13 575333e1c71f85026d3e3933.json,v
> root@school-server:/data/rcs-repo/Nodes/3/3/3# ls -l575333e1c71f85026d3e3833.json
> ls: invalid option -- '5'
> Try 'ls --help' for more information.
> root@school-server:/data/rcs-repo/Nodes/3/3/3# ls -l 575333e1c71f85026d3e3833.json
> -rw-r--r-- 1 500 500 1851 Jun 27 19:13 575333e1c71f85026d3e3833.json
> root@school-server:/data/rcs-repo/Nodes/3/3/3# ls 575333e1c71f85026d3e3833.json
> 575333e1c71f85026d3e3833.json
> root@school-server:/data/rcs-repo/Nodes/3/3/3#

**Comment by katkamrachana** [comment]
Thanks for informing. Will get back to you soon @alpeshgajbe

**Comment by katkamrachana** [comment]
Fixed in #1692
