### ISSUE TITLE
The list of buddies persist in new page created after removing the buddy.

### ISSUE THREAD

**Issue by udnshah** [gnowledge/gstudio#1520]
The list of buddies persist in new page created after removing the buddy.

![screenshot from 2016-07-08 20 07 52](https://cloud.githubusercontent.com/assets/12168016/16690920/d76da44c-4547-11e6-9200-491fc132575f.png)
![screenshot from 2016-07-08 20 07 57](https://cloud.githubusercontent.com/assets/12168016/16690921/d775e81e-4547-11e6-8797-7ead75531108.png)

**Comment by katkamrachana** [comment]
This is fixed in #1531
