### ISSUE TITLE
Delete user in admin panel giving "500 - Internal Server Error"

### ISSUE THREAD

**Issue by mrunal4** [gnowledge/gstudio#1535]
Clicking on delete button to delete user reverts "500 - Internal Server Error". Screenshots are attached for the references.

![screenshot from 2016-08-02 13-27-04](https://cloud.githubusercontent.com/assets/12952961/17321223/0fa2e180-58b5-11e6-8478-6b24fc67f140.png)

![screenshot from 2016-08-02 13-27-11](https://cloud.githubusercontent.com/assets/12952961/17321224/0faa22a6-58b5-11e6-90ae-c7c9e97561a8.png)

**Comment by katkamrachana** [comment]
User objects should **NOT** be deleted from django's admin-panel. Thankfully, it threw some error and aborted. 

gStudio has dependencies with these user instances and hence the deletion **must** be through mongodb and then django's dB. Currently, we do not have any option for user deletion other than proceeding with a script. That can be added as a separate issue though.

Am closing this one as it is irrelevant for debug.
