### ISSUE TITLE
On editing uploaded file, getting "500 - internal server error".

### ISSUE THREAD

**Issue by SatejG** [gnowledge/gstudio#1541]
On editing title or content of already uploaded file, getting "500 - internal server error",
but changes getting saved.

**Comment by katkamrachana** [comment]
@SatejG Was this tested on any live server or on local copy? If on live one, which server was that? If local, can you re-test it with latest pull.

**Comment by katkamrachana** [comment]
This issue is not reported in recent commits. Closing this issue now. Please re-open if more clarification is needed.
