### ISSUE TITLE
"gstudio" link at the footer of the site not proper

### ISSUE THREAD

**Issue by SatejG** [gnowledge/gstudio#1551]
Link provided under "gstudio" at the footer is not proper.

**Comment by katkamrachana** [comment]
_gstudio_ link earlier redirected to static commit-hash. This has been resolved by @kedar2a in [this](https://github.com/gnowledge/gstudio/commit/e3260a8d6cf8bd32dd953943afad13e8241c4491) commit.

If this is not what you meant, please re-open and elaborate the issue.
