### ISSUE TITLE
Metastudio: Need functionality for listing all events

### ISSUE THREAD

**Issue by SatejG** [gnowledge/gstudio#1558]
Metastudio:
Functionality needed for listing all the events at one place. (Further we can improve this so as to list the events according to time span specified for listing).

**Comment by katkamrachana** [comment]
Noted in Issue [49](https://gitlab.com/gnowledge/gstudio/issues/49) of gitlab.
Fixed in [this](https://github.com/gnowledge/gstudio/pull/1382/commits/79206198ebf923849c0a5e56b60431c1e1e11810) commit.

Reopen this issue if this is not meant for ProgramEvents along with elaboration.
