### ISSUE TITLE
Extra Checkbox in quiz

### ISSUE THREAD

**Issue by TanviB25** [gnowledge/gstudio#1600]
Reference: http://103.36.84.136/invitation2clix-hindi/gcourse/course_section/57927170a6127d01f8e8663c/57927173a6127d01f8e8668a/57927173a6127d01f8e8668c/

With above reference url, found extra checkbox in page.

![extra_checkbox](https://cloud.githubusercontent.com/assets/19238176/22395075/8e298128-e558-11e6-9c84-4322d9f0357e.png)

**Comment by katkamrachana** [comment]
The additional[empty/unnecessary] option is truncated. Data issue.
