### ISSUE TITLE
Upload File Gallery: Unable to upload images: .png/.jpg formats and notebook exercise

### ISSUE THREAD

**Issue by TanviB25** [gnowledge/gstudio#1603]
Reference: http://103.36.84.136/57927168a6127d01f8e86574/group/upload_using_save_file/
With reference to above url, when I tried to upload new images in gallery, can't upload any given formats in .png/.jpg format. It gives internal server error.
![server_error](https://cloud.githubusercontent.com/assets/19238176/22396363/d0fa9454-e57d-11e6-803d-97a14ae83431.png)
![error_occured](https://cloud.githubusercontent.com/assets/19238176/22396516/55e67bda-e581-11e6-9479-4a698ce22e4c.png)

**Comment by saavrabh** [comment]
@TanviB25  can you please specify last 3 or 5 commit numbers of this instance? 
You can check it by using `git log` command.

**Comment by mrunal4** [comment]
@saavrabh : You can get ssh access of that system with core user.

password for it is default core password.

**Comment by udnshah** [comment]
@TanviB25,
The virtual machine you have mentioned above (http://103.36.84.136/) has approx disk size of 95 GB
and the disk is fully utilized.

Hence the file upload is giving internal server error.

I request @mrunal4 and Alpesh to increase the disk space and then again you check this same scenario.

Thank you,

**Comment by mrunal4** [comment]
@udnshah Rightly pointed the issue.
I had resolved the issue. Now you and @TanviB25  can resume testing sessions again on (http://103.36.84.136/).

**Comment by katkamrachana** [comment]
Thanks @mrunal4
