### ISSUE TITLE
Browser auto saves username and password for new session

### ISSUE THREAD

**Issue by TanviB25** [gnowledge/gstudio#1609]
Reference: http://103.36.84.149/welcome 
With reference to above url, when user logged in and close the browser, for a new session it should ask for login and password for continuing activity. Except in incognito mode, user automatically able to login into same session.

**Comment by kedar2a** [comment]
- This is default/standard behaviour. Unless and until you are logging out, session will preserved.
- In incognito/private window of browser, volatile session is created which gets wiped out as on when window is closed.
